CUDA_VISIBLE_DEVICES=0 python train.py \
   --expname train_scared\
   --use_viewdirs True\
   --dataset_name scared \
   --datadir <your_scared_data_folder> \
   --view_num 7 \
   --num_epochs 30 \
   --lrate 2e-4 \
   --patch_size 6 \
   --patch_num 50 \
   --ckpt ./pretrained_weights/ucnerf.tar